[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[start]
cmd = "npx prisma migrate deploy && node dist/index.js"
